# Generated by Django 4.2.6 on 2023-12-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Api_App', '0004_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
