# Generated by Django 4.2.6 on 2024-01-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Api_App', '0010_remove_blog_user_alter_blog_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
        migrations.AlterModelTable(
            name='blogs',
            table=None,
        ),
    ]
